name: Notificar Pull Request con Gmail

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Enviar correo con Gmail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Nuevo Pull Request"
        to: "smxbijovanovich@gmail.com"
        from: "GitHub Notifier <${{ secrets.EMAIL_USERNAME }}>"
        body: |
          Correo enviado por hacer un pull request
